import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar/Navbar";
// import { SessionProvider } from 'next-auth/react';
import { Auth } from "../components/Auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
require("dotenv").config();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
      {children}
        <Footer />
      </body>
    </html>
  );
}
