import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar/Navbar";
// import { SessionProvider } from 'next-auth/react';
// import { Auth } from "../components/Auth";
import  AuthProvider  from "../components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HealthCheck",
  description: "Generated by create next app",
};
require("dotenv").config();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider>
        <main>
        <Navbar />
      {children}
        <Footer /></main></AuthProvider>
      </body>
    </html>
  );
}
